# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Rabin shrestha
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://nandomoreira.me
baseurl: "/Rabin Shrestha"
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name      : Rabin shrestha
  job       : Full stack developer
  bio       : "rails developer with react and foundation as hammer and wrench :D"
  thumb     : /images/author.jpg
  email     : danieldangol@gmail.com
  # url       : https://nandomoreira.me
  github    : https://github.com/jyapujuju
  twitter   : https://twitter.com/rabinshrestha88
  facebook  : https://facebook.com/rabin.shrestha.161214
  linkedin  : http://linkedin.com/in/rabin-shrestha-9b0b0442
  codepen   : https://codepen.io/jyapujuju/


# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
